# Generated by Django 6.0.6 on 2026-06-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
