# Generated by Django 6.0.6 on 2026-07-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberos', '0001_initial'),
        ('citas', '0010_cita_productos'),
        ('clientes', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barbero',
        ),
        migrations.AlterField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='barberos.barbero'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.servicio'),
        ),
    ]
