# Generated by Django 4.2.23 on 2026-07-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_delete_barbero_alter_cita_barbero_alter_cita_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
