# Generated by Django 4.2.23 on 2026-07-02 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberos', '0001_initial'),
        ('citas', '0012_alter_cita_id_alter_servicio_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.AlterField(
            model_name='cita',
            name='adicionales',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='barberos.barbero'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='productos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.IntegerField(help_text='Duración en minutos'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('barbero', 'fecha', 'hora'), name='cita_unica_por_barbero'),
        ),
    ]
