# Generated by Django 4.2.23 on 2026-07-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberos', '0001_initial'),
        ('citas', '0013_alter_cita_options_alter_cita_adicionales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='adicionales',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='barberos.barbero'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='productos',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración en minutos'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
